# Copyright 2023 OmniSafeAI Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""
RMP (Riemannian Motion Policy) Corrector for Multi-Agent Reinforcement Learning

This module provides RMP-based action correction for multi-agent systems,
including collision avoidance and formation control.
"""

import sys
import numpy as np
import torch

from safepo.multi_agent.formation_spec import build_formation_edges

sys.path.insert(0, '/workspace/multi-robot-rmpflow')
try:
    from rmp import RMPRoot, RMPNode
    from rmp_leaf import (
        CollisionAvoidance,
        CollisionAvoidanceDecentralized,
        FormationDecentralized,
        FormationOrientationDecentralized,
    )
    RMP_AVAILABLE = True
except ImportError:
    print("Warning: RMP modules not available. RMP correction will be disabled.")
    RMP_AVAILABLE = False


def _formation_hub_psi(y):
    y = np.asarray(y, dtype=np.float64)
    if y.ndim == 1:
        y = y.reshape(-1, 1)
    return np.copy(y)


def _formation_hub_J(_y):
    return np.eye(2, dtype=np.float64)


def _formation_hub_Jdot(_y, _yd):
    return np.zeros((2, 2), dtype=np.float64)


class RMPCorrector:
    """
    RMP-based action corrector for multi-agent systems.
    
    This class manages RMP trees for collision avoidance and formation control,
    and applies corrections to actions generated by RL policies.
    """
    
    def __init__(
        self,
        num_agents: int,
        num_envs: int,
        device: str,
        config: dict = None
    ):
        """
        初始化 RMP 修正器
        
        参数:
            num_agents: 机器人数量
            num_envs: 并行环境数量
            device: 计算设备（'cpu' 或 'cuda'）
            config: 配置字典，包含以下可选参数:
                - use_rmp: 是否启用 RMP (默认 True)
                - formation_target_distance: 编队目标距离 / 邻距 spacing (默认 0.5)
                - formation_shape: mesh | line | wedge | circle — mesh 全连接；
                  line 链式；wedge V 字；circle 正则 N 边形闭环（spacing 为邻接弦长）(默认 mesh)
                - formation_line_axis: line 时 x (横排 +x) 或 y (纵排 +y) (默认 x)
                - formation_wedge_half_angle_deg: wedge 半张角，度 (默认 35)
                - formation_desired_direction: 仅 mesh：统一期望边方向 \\hat r_ij^* (默认 [0, 1])
                - formation_orientation_alpha: 方向任务 \\alpha_\\theta (默认 1.0)
                - formation_orientation_eta: 方向任务 \\eta_\\theta (默认 2.0)
                - formation_orientation_c_metric: 方向任务度量 M_\\theta=c_\\theta (默认 10.0)
                - collision_safety_radius: 碰撞安全半径 (默认 0.3)
                - rmp_weight: RMP 修正权重 (默认 0.1)
        """
        self.num_agents = num_agents
        self.num_envs = num_envs
        self.device = device
        self.config = config or {}
        
        # 从配置获取参数
        self.rmp_enabled = RMP_AVAILABLE and self.config.get('use_rmp', True)
        self.formation_target_distance = self.config.get('formation_target_distance', 0.5)
        self.formation_shape = str(self.config.get('formation_shape', 'mesh')).strip().lower()
        self.formation_line_axis = str(self.config.get('formation_line_axis', 'x')).strip().lower()
        self.formation_wedge_half_angle_deg = float(
            self.config.get('formation_wedge_half_angle_deg', 35.0)
        )
        self.formation_desired_direction = np.asarray(
            self.config.get('formation_desired_direction', [0.0, 1.0]),
            dtype=np.float64,
        ).reshape(2)
        self.formation_orientation_alpha = self.config.get('formation_orientation_alpha', 1.0)
        self.formation_orientation_eta = self.config.get('formation_orientation_eta', 2.0)
        self.formation_orientation_c_metric = self.config.get('formation_orientation_c_metric', 10.0)
        self.collision_safety_radius = self.config.get('collision_safety_radius', 0.3)
        # 提高 RMP 修正在最终动作中的权重（默认从 0.1 提高到 0.5）
        self.rmp_weight = self.config.get('rmp_weight', 1)
        
        # 初始化 RMP 树
        self.rmp_trees = None
        self.rmp_robots = None
        self.rmp_collision_nodes = None
        self.rmp_formation_nodes = None
        self.rmp_sigwall_nodes = None
        self.formation_edges = []

        if self.rmp_enabled:
            try:
                wedge_rad = np.deg2rad(self.formation_wedge_half_angle_deg)
                self.formation_edges = build_formation_edges(
                    self.formation_shape,
                    self.num_agents,
                    self.formation_target_distance,
                    self.formation_desired_direction,
                    line_axis=self.formation_line_axis,
                    wedge_half_angle_rad=wedge_rad,
                )
                self._init_rmp_trees()
                print(
                    f"RMP enabled: shape={self.formation_shape}, "
                    f"n_formation_edges={len(self.formation_edges)}, "
                    f"spacing={self.formation_target_distance}, "
                    f"collision_radius={self.collision_safety_radius}, weight={self.rmp_weight}"
                )
            except Exception as e:
                print(f"Warning: Failed to initialize RMP trees: {e}. RMP will be disabled.")
                self.rmp_enabled = False
        else:
            if not RMP_AVAILABLE:
                print("RMP modules not available. RMP correction disabled.")
    
    def _init_rmp_trees(self):
        """初始化每个环境的 RMP 树"""
        if not RMP_AVAILABLE:
            raise ImportError("RMP modules are not available")
        
        self.rmp_trees = []
        self.rmp_robots = []
        self.rmp_collision_nodes = []
        self.rmp_formation_nodes = []
        self.rmp_sigwall_nodes = []
        
        for env_idx in range(self.num_envs):
            # 为每个环境创建 RMP 树
            r = RMPRoot('root_env_' + str(env_idx))
            
            # 创建机器人节点
            robots = []
            def create_mappings(i):
                phi = lambda y, i=i: np.array([[y[2 * i, 0]], [y[2 * i + 1, 0]]])
                J = lambda y, i=i: np.concatenate((
                        np.zeros((2, 2 * i)),
                        np.eye(2),
                        np.zeros((2, 2 * (self.num_agents - i - 1)))), axis=1)
                J_dot = lambda y, y_dot: np.zeros((2, 2 * self.num_agents))
                return phi, J, J_dot
            
            for i in range(self.num_agents):
                phi, J, J_dot = create_mappings(i)
                robot = RMPNode('robot_' + str(i), r, phi, J, J_dot)
                robots.append(robot)
            
            # 创建机器人之间的碰撞避免节点
            collision_nodes = []
            for i in range(self.num_agents):
                for j in range(self.num_agents):
                    if i != j:
                        ca = CollisionAvoidanceDecentralized(
                            'ca_robot_' + str(i) + '_robot_' + str(j),
                            robots[i],
                            robots[j],
                            R=self.collision_safety_radius,
                            eta=1.0)
                        collision_nodes.append(ca)
            
            # 创建编队控制：按 formation_spec 的边列表；每条边在 robot[i] 上挂
            # hub + 距离叶 + 方向叶（i 指向 j，几何见 formation_spec 注记）
            formation_nodes = []
            for edge_idx, (i, j, d_ij, r_star) in enumerate(self.formation_edges):
                hub = RMPNode(
                    f'formation_hub_e{edge_idx}_robot_{i}_to_{j}',
                    robots[i],
                    _formation_hub_psi,
                    _formation_hub_J,
                    _formation_hub_Jdot,
                )
                fc = FormationDecentralized(
                    f'fc_dist_e{edge_idx}_robot_{i}_to_{j}',
                    hub,
                    robots[j],
                    d=d_ij,
                    gain=1.0,
                    eta=2.0,
                    w=10.0,
                )
                fo = FormationOrientationDecentralized(
                    f'fc_ori_e{edge_idx}_robot_{i}_to_{j}',
                    hub,
                    robots[j],
                    r_star=r_star,
                    alpha_theta=self.formation_orientation_alpha,
                    eta_theta=self.formation_orientation_eta,
                    c_theta=self.formation_orientation_c_metric,
                )
                formation_nodes.append(fc)
                formation_nodes.append(fo)

            # 创建与 Sigwalls 碰撞避免的节点（静态障碍物）
            # MultiFormationGoalLevel0 中 sigwalls.locations 固定为 [(-0.8, 0), (0.8, 0)]
            sigwall_centers = [np.array([-0.8, 0.0]), np.array([0.8, 0.0])]
            sigwall_radius = self.collision_safety_radius
            sigwall_nodes = []
            for i in range(self.num_agents):
                for wall_idx, center in enumerate(sigwall_centers):
                    ca_wall = CollisionAvoidance(
                        f'ca_robot_{i}_sigwall_{wall_idx}',
                        robots[i],
                        None,
                        c=center,
                        R=sigwall_radius,
                        epsilon=1e-3,
                        alpha=1e-5,
                        eta=1.0,
                    )
                    sigwall_nodes.append(ca_wall)
            
            self.rmp_trees.append(r)
            self.rmp_robots.append(robots)
            self.rmp_collision_nodes.append(collision_nodes)
            self.rmp_formation_nodes.append(formation_nodes)
            self.rmp_sigwall_nodes.append(sigwall_nodes)
    
    def apply_correction(
        self,
        actions: list,
        agent_positions: list,
        agent_velocities: list
    ) -> list:
        """
        使用 RMP 修正动作
        
        参数:
            actions: List[torch.Tensor], 每个 agent 的动作 [n_envs, action_dim]
            agent_positions: List[np.ndarray], 每个 agent 的位置 [n_envs, 2]
            agent_velocities: List[np.ndarray], 每个 agent 的速度 [n_envs, 2]
        
        返回:
            corrected_actions: List[torch.Tensor], 修正后的动作
        """
        if not self.rmp_enabled or self.rmp_trees is None:
            return actions
        
        corrected_actions = []
        
        for env_idx in range(self.num_envs):
            # 构建状态向量 [x0, y0, x1, y1, ...]
            x = np.zeros((2 * self.num_agents, 1))
            x_dot = np.zeros((2 * self.num_agents, 1))
            
            for i in range(self.num_agents):
                pos = agent_positions[i][env_idx]
                vel = agent_velocities[i][env_idx]
                
                # 处理 torch.Tensor 或 numpy array
                if isinstance(pos, torch.Tensor):
                    pos = pos.cpu().numpy()
                if isinstance(vel, torch.Tensor):
                    vel = vel.cpu().numpy()
                
                x[2*i:2*i+2, 0] = pos[:2]  # 只取 x, y
                x_dot[2*i:2*i+2, 0] = vel[:2] if len(vel) >= 2 else np.zeros(2)
            
            # 更新 RMP 树
            r = self.rmp_trees[env_idx]
            r.set_root_state(x, x_dot)
            r.pushforward()
            
            # 更新碰撞和编队节点
            for node in self.rmp_collision_nodes[env_idx]:
                node.update()
            for node in self.rmp_formation_nodes[env_idx]:
                node.update()
            # Sigwalls 为静态障碍物，其 psi/J 在初始化时已固定，
            # 这里只依赖于机器人位姿，因此无需在每步单独更新参数。
            
            r.pullback()
            
            # 解析得到加速度修正
            try:
                acceleration_correction = r.resolve()  # [2*num_agents, 1]
                
                # 将加速度修正转换为动作修正（假设动作是速度指令）
                # 对于每个 agent，取对应的加速度修正
                env_corrected_actions = []
                for i in range(self.num_agents):
                    accel_corr = acceleration_correction[2*i:2*i+2, 0]
                    # 将加速度修正添加到原始动作（假设动作空间是速度）
                    original_action = actions[i][env_idx]
                    if isinstance(original_action, torch.Tensor):
                        original_action = original_action.cpu().numpy()
                    
                    # 限制修正幅度，避免过大
                    corrected_action = original_action + self.rmp_weight * accel_corr[:len(original_action)]
                    env_corrected_actions.append(torch.from_numpy(corrected_action).to(self.device))
                
                if env_idx == 0:
                    corrected_actions = [[ac] for ac in env_corrected_actions]
                else:
                    for i in range(self.num_agents):
                        corrected_actions[i].append(env_corrected_actions[i])
            except Exception as e:
                # 如果 RMP 求解失败，使用原始动作
                if env_idx == 0:
                    corrected_actions = [[actions[i][env_idx]] for i in range(self.num_agents)]
                else:
                    for i in range(self.num_agents):
                        corrected_actions[i].append(actions[i][env_idx])
        
        # 转换为正确的格式
        final_actions = []
        for i in range(self.num_agents):
            final_actions.append(torch.stack(corrected_actions[i]))
        
        return final_actions
    
    def get_agent_positions_from_env(self, envs, n_envs: int) -> tuple:
        """
        从环境中获取 agent 位置和速度
        
        参数:
            envs: 向量化环境对象
            n_envs: 环境数量
        
        返回:
            (agent_positions, agent_velocities): 位置和速度列表
        """
        agent_positions = []
        agent_velocities = []
        
        # 对于向量化环境，从每个子环境获取位置
        if hasattr(envs, 'envs') and len(envs.envs) > 0:
            # 向量化环境
            for env_idx in range(min(n_envs, len(envs.envs))):
                env = envs.envs[env_idx]
                if hasattr(env, 'env') and hasattr(env.env, 'task') and hasattr(env.env.task, 'agent'):
                    agent = env.env.task.agent
                    env_positions = []
                    env_velocities = []
                    for i in range(self.num_agents):
                        # 获取 agent 位置（pos_0, pos_1, ...）
                        pos_attr = getattr(agent, f'pos_{i}', None)
                        if pos_attr is not None:
                            pos = pos_attr[:2]  # 只取 x, y
                        else:
                            pos = np.zeros(2)
                        
                        # 获取 agent 速度（vel_0, vel_1, ...）
                        vel_attr = getattr(agent, f'vel_{i}', None)
                        if vel_attr is not None:
                            vel = vel_attr[:2]  # 只取 x, y 方向速度
                        else:
                            vel = np.zeros(2)
                        
                        env_positions.append(pos)
                        env_velocities.append(vel)
                    
                    if env_idx == 0:
                        agent_positions = [[pos] for pos in env_positions]
                        agent_velocities = [[vel] for vel in env_velocities]
                    else:
                        for i in range(self.num_agents):
                            agent_positions[i].append(env_positions[i])
                            agent_velocities[i].append(env_velocities[i])
            
            # 转换为 numpy 数组
            for i in range(self.num_agents):
                agent_positions[i] = np.array(agent_positions[i])
                agent_velocities[i] = np.array(agent_velocities[i])
        else:
            # 如果无法获取，使用零向量作为占位符
            for i in range(self.num_agents):
                agent_positions.append(np.zeros((n_envs, 2)))
                agent_velocities.append(np.zeros((n_envs, 2)))
        
        return agent_positions, agent_velocities

