# Copyright 2023 OmniSafeAI Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""
RMP (Riemannian Motion Policy) Corrector for Multi-Agent Reinforcement Learning

This module provides RMP-based action correction for multi-agent systems,
including collision avoidance and formation control.
"""

import sys
import numpy as np
import torch

from safepo.multi_agent.formation_spec import build_formation_edges

# [MOD 2026-04-18] 支持本地/容器两种运行环境:
#   1. 环境变量 MULTI_ROBOT_RMPFLOW_PATH 最高优先级
#   2. Docker 容器默认路径 /workspace/multi-robot-rmpflow
#   3. 相对于本文件的 submodule 路径 <repo>/algorithms/multi-robot-rmpflow (本地开发)
import os as _os
_rmp_candidates = []
if _os.environ.get('MULTI_ROBOT_RMPFLOW_PATH'):
    _rmp_candidates.append(_os.environ['MULTI_ROBOT_RMPFLOW_PATH'])
_rmp_candidates.append('/workspace/multi-robot-rmpflow')
_rmp_candidates.append(
    _os.path.abspath(
        _os.path.join(
            _os.path.dirname(__file__), '..', '..', '..', 'multi-robot-rmpflow'
        )
    )
)
for _p in _rmp_candidates:
    if _os.path.isdir(_p) and _os.path.isfile(_os.path.join(_p, 'rmp.py')):
        sys.path.insert(0, _p)
        break

try:
    from rmp import RMPRoot, RMPNode
    from rmp_leaf import (
        CollisionAvoidance,
        CollisionAvoidanceDecentralized,
        FormationDecentralized,
        FormationOrientationDecentralized,
        RLLeaf,  # [ADD 2026-04-18] path A: RL-as-leaf integration
    )
    RMP_AVAILABLE = True
except ImportError:
    print("Warning: RMP modules not available. RMP correction will be disabled.")
    RMP_AVAILABLE = False


def _formation_hub_psi(y):
    y = np.asarray(y, dtype=np.float64)
    if y.ndim == 1:
        y = y.reshape(-1, 1)
    return np.copy(y)


def _formation_hub_J(_y):
    return np.eye(2, dtype=np.float64)


def _formation_hub_Jdot(_y, _yd):
    return np.zeros((2, 2), dtype=np.float64)


class RMPCorrector:
    """
    RMP-based action corrector for multi-agent systems.
    
    This class manages RMP trees for collision avoidance and formation control,
    and applies corrections to actions generated by RL policies.
    """
    
    def __init__(
        self,
        num_agents: int,
        num_envs: int,
        device: str,
        config: dict = None
    ):
        """
        初始化 RMP 修正器
        
        参数:
            num_agents: 机器人数量
            num_envs: 并行环境数量
            device: 计算设备（'cpu' 或 'cuda'）
            config: 配置字典，包含以下可选参数:
                - use_rmp: 是否启用 RMP (默认 True)
                - formation_target_distance: 编队目标距离 / 邻距 spacing (默认 0.5)
                - formation_shape: mesh | line | wedge | circle — mesh 全连接；
                  line 链式；wedge V 字；circle 正则 N 边形闭环（spacing 为邻接弦长）(默认 mesh)
                - formation_line_axis: line 时 x (横排 +x) 或 y (纵排 +y) (默认 x)
                - formation_wedge_half_angle_deg: wedge 半张角，度 (默认 35)
                - formation_desired_direction: 仅 mesh：统一期望边方向 \\hat r_ij^* (默认 [0, 1])
                - formation_orientation_alpha: 方向任务 \\alpha_\\theta (默认 1.0)
                - formation_orientation_eta: 方向任务 \\eta_\\theta (默认 2.0)
                - formation_orientation_c_metric: 方向任务度量 M_\\theta=c_\\theta (默认 10.0)
                - collision_safety_radius: 碰撞安全半径 (默认 0.3)
                - rmp_weight: RMP 修正权重 (默认 0.1)
        """
        self.num_agents = num_agents
        self.num_envs = num_envs
        self.device = device
        self.config = config or {}
        
        # 从配置获取参数
        self.rmp_enabled = RMP_AVAILABLE and self.config.get('use_rmp', True)
        self.use_rmp_collision = bool(self.config.get('use_rmp_collision', True))
        self.use_rmp_formation = bool(self.config.get('use_rmp_formation', True))
        if not (self.use_rmp_collision or self.use_rmp_formation):
            self.rmp_enabled = False
        self.formation_target_distance = self.config.get('formation_target_distance', 0.5)
        self.formation_shape = str(self.config.get('formation_shape', 'mesh')).strip().lower()
        self.formation_line_axis = str(self.config.get('formation_line_axis', 'x')).strip().lower()
        self.formation_wedge_half_angle_deg = float(
            self.config.get('formation_wedge_half_angle_deg', 35.0)
        )
        self.formation_desired_direction = np.asarray(
            self.config.get('formation_desired_direction', [0.0, 1.0]),
            dtype=np.float64,
        ).reshape(2)
        self.formation_orientation_alpha = self.config.get('formation_orientation_alpha', 1.0)
        self.formation_orientation_eta = self.config.get('formation_orientation_eta', 2.0)
        self.formation_orientation_c_metric = self.config.get('formation_orientation_c_metric', 10.0)
        self.collision_safety_radius = self.config.get('collision_safety_radius', 0.3)
        # [DEPRECATED 2026-04-18] rmp_weight 仅在 additive 融合模式下生效;
        # 路径 A 启用后 RL 作为叶节点参与 pullback, 融合权重由 rl_leaf_weight 控制.
        self.rmp_weight = self.config.get('rmp_weight', 1)
        # [ADD 2026-04-18] 融合模式与 RL 叶节点权重
        #   fusion_mode = 'leaf'     : RL 作为 RMP 叶节点参与 pushforward/pullback/resolve (默认, 路径 A)
        #   fusion_mode = 'additive' : 旧版 a_final = a_RL + rmp_weight * a_RMP 线性加权 (回退)
        self.fusion_mode = str(self.config.get('fusion_mode', 'leaf')).strip().lower()
        self.rl_leaf_weight = float(self.config.get('rl_leaf_weight', 10.0))
        # [ADD 2026-04-18 sweep] 环境变量覆盖 (run_chap4.sh sweep 模式用):
        #   CHAP4_FUSION_MODE_OVERRIDE       ∈ {"leaf", "additive"}
        #   CHAP4_RL_LEAF_WEIGHT_OVERRIDE    ∈ float (e.g. 10.0 for GCPL, 0.01 for RMPflow-only)
        _env_fm = _os.environ.get('CHAP4_FUSION_MODE_OVERRIDE', '').strip().lower()
        if _env_fm in ('leaf', 'additive'):
            self.fusion_mode = _env_fm
        _env_w = _os.environ.get('CHAP4_RL_LEAF_WEIGHT_OVERRIDE', '').strip()
        if _env_w:
            try:
                self.rl_leaf_weight = float(_env_w)
            except ValueError:
                pass
        # [ADD 2026-04-19 ablation] 三类几何叶节点独立开关 (chap4 RQ2 消融实验用).
        #   use_formation_leaf    : FormationDecentralized (距离保持)
        #   use_orientation_leaf  : FormationOrientationDecentralized (方向保持, 本文新增)
        #   use_collision_leaf    : CollisionAvoidanceDecentralized + 静态障碍 (sigwalls)
        # 默认全开 (完整 GCPL). 环境变量 CHAP4_USE_*_LEAF 支持 sweep 脚本覆盖.
        def _env_bool(name, default):
            v = _os.environ.get(name, '').strip().lower()
            if v in ('1', 'true', 'yes', 'on'):
                return True
            if v in ('0', 'false', 'no', 'off'):
                return False
            return default
        self.use_formation_leaf = _env_bool(
            'CHAP4_USE_FORMATION_LEAF',
            bool(self.config.get('use_formation_leaf', True)),
        )
        self.use_orientation_leaf = _env_bool(
            'CHAP4_USE_ORIENTATION_LEAF',
            bool(self.config.get('use_orientation_leaf', True)),
        )
        self.use_collision_leaf = _env_bool(
            'CHAP4_USE_COLLISION_LEAF',
            bool(self.config.get('use_collision_leaf', True)),
        )

        # [ADD 2026-04-18 缺口 1] chap4.4.4 差速映射
        #   RMP resolve 输出是世界坐标 (ax, ay); Point agent 的动作空间是机体系 (v, omega).
        #   paper 4.4.4 给出映射: v = cos(θ)ax + sin(θ)ay,  omega = k_θ(atan2(ay,ax) - θ).
        #   开启后在 fusion_mode='leaf' 下对 resolve 输出做此转换, 再送给 env.
        self.use_diff_drive_mapping = bool(self.config.get('use_diff_drive_mapping', True))
        self.diff_drive_k_theta = float(self.config.get('diff_drive_k_theta', 1.0))

        # 初始化 RMP 树
        self.rmp_trees = None
        self.rmp_robots = None
        self.rmp_collision_nodes = None
        self.rmp_formation_nodes = None
        self.rmp_sigwall_nodes = None
        self.rmp_rl_nodes = None  # [ADD 2026-04-18] 每环境 x 每机器人 的 RLLeaf
        self.formation_edges = []

        if self.rmp_enabled:
            try:
                wedge_rad = np.deg2rad(self.formation_wedge_half_angle_deg)
                self.formation_edges = build_formation_edges(
                    self.formation_shape,
                    self.num_agents,
                    self.formation_target_distance,
                    self.formation_desired_direction,
                    line_axis=self.formation_line_axis,
                    wedge_half_angle_rad=wedge_rad,
                )
                self._init_rmp_trees()
                print(
                    f"RMP enabled: shape={self.formation_shape}, "
                    f"collision_nodes={'on' if self.use_rmp_collision else 'off'}, "
                    f"formation_nodes={'on' if self.use_rmp_formation else 'off'}, "
                    f"n_formation_edges={len(self.formation_edges)}, "
                    f"spacing={self.formation_target_distance}, "
                    f"collision_radius={self.collision_safety_radius}, "
                    f"fusion_mode={self.fusion_mode}, "
                    f"rl_leaf_weight={self.rl_leaf_weight}, "
                    f"diff_drive_mapping={self.use_diff_drive_mapping} "
                    f"(k_theta={self.diff_drive_k_theta}), "
                    f"legacy_rmp_weight={self.rmp_weight}, "
                    f"leaves=[form:{int(self.use_formation_leaf)}, "
                    f"orient:{int(self.use_orientation_leaf)}, "
                    f"coll:{int(self.use_collision_leaf)}]"
                )
            except Exception as e:
                print(f"Warning: Failed to initialize RMP trees: {e}. RMP will be disabled.")
                self.rmp_enabled = False
        else:
            if not RMP_AVAILABLE:
                print("RMP modules not available. RMP correction disabled.")
    
    def _init_rmp_trees(self):
        """初始化每个环境的 RMP 树"""
        if not RMP_AVAILABLE:
            raise ImportError("RMP modules are not available")
        
        self.rmp_trees = []
        self.rmp_robots = []
        self.rmp_collision_nodes = []
        self.rmp_formation_nodes = []
        self.rmp_sigwall_nodes = []
        self.rmp_rl_nodes = []  # [ADD 2026-04-18]

        for env_idx in range(self.num_envs):
            # 为每个环境创建 RMP 树
            r = RMPRoot('root_env_' + str(env_idx))
            
            # 创建机器人节点
            robots = []
            def create_mappings(i):
                phi = lambda y, i=i: np.array([[y[2 * i, 0]], [y[2 * i + 1, 0]]])
                J = lambda y, i=i: np.concatenate((
                        np.zeros((2, 2 * i)),
                        np.eye(2),
                        np.zeros((2, 2 * (self.num_agents - i - 1)))), axis=1)
                J_dot = lambda y, y_dot: np.zeros((2, 2 * self.num_agents))
                return phi, J, J_dot
            
            for i in range(self.num_agents):
                phi, J, J_dot = create_mappings(i)
                robot = RMPNode('robot_' + str(i), r, phi, J, J_dot)
                robots.append(robot)
            
            # 创建机器人之间的碰撞避免节点 (可被 use_collision_leaf 关闭做消融)
            collision_nodes = []
            if self.use_rmp_collision and self.use_collision_leaf:
                for i in range(self.num_agents):
                    for j in range(self.num_agents):
                        if i != j:
                            ca = CollisionAvoidanceDecentralized(
                                'ca_robot_' + str(i) + '_robot_' + str(j),
                                robots[i],
                                robots[j],
                                R=self.collision_safety_radius,
                                eta=1.0)
                            collision_nodes.append(ca)
            # 创建编队控制：按 formation_spec 的边列表；每条边在 robot[i] 上挂
            # hub + 距离叶 + 方向叶（i 指向 j，几何见 formation_spec 注记）
            # use_formation_leaf / use_orientation_leaf 分别控制距离/方向叶 (消融用)
            formation_nodes = []
            if self.use_rmp_formation and (self.use_formation_leaf or self.use_orientation_leaf):
                for edge_idx, (i, j, d_ij, r_star) in enumerate(self.formation_edges):
                    hub = RMPNode(
                        f'formation_hub_e{edge_idx}_robot_{i}_to_{j}',
                        robots[i],
                        _formation_hub_psi,
                        _formation_hub_J,
                        _formation_hub_Jdot,
                    )
                    if self.use_formation_leaf:
                        fc = FormationDecentralized(
                            f'fc_dist_e{edge_idx}_robot_{i}_to_{j}',
                            hub,
                            robots[j],
                            d=d_ij,
                            gain=1.0,
                            eta=2.0,
                            w=10.0,
                        )
                        formation_nodes.append(fc)
                    if self.use_orientation_leaf:
                        fo = FormationOrientationDecentralized(
                            f'fc_ori_e{edge_idx}_robot_{i}_to_{j}',
                            hub,
                            robots[j],
                            r_star=r_star,
                            alpha_theta=self.formation_orientation_alpha,
                            eta_theta=self.formation_orientation_eta,
                            c_theta=self.formation_orientation_c_metric,
                        )
                        formation_nodes.append(fo)

            # 创建与 Sigwalls 碰撞避免的节点（静态障碍物）
            # MultiFormationGoalLevel0 中 sigwalls.locations 实际为 [(-1.0, 0), (1.0, 0)]
            # 支持通过 config["sigwall_centers"] 覆盖；若未提供则使用任务默认值
            # use_collision_leaf 关闭时同时禁用 sigwall 碰撞 (保证"A 档裸 MAPPO"纯净)
            sigwall_nodes = []
            if self.use_rmp_collision and self.use_collision_leaf:
                _default_sigwall_centers = [[-1.0, 0.0], [1.0, 0.0]]
                _cfg_sigwall_centers = self.config.get('sigwall_centers', _default_sigwall_centers)
                sigwall_centers = [np.asarray(c, dtype=np.float64) for c in _cfg_sigwall_centers]
                sigwall_radius = self.collision_safety_radius
                for i in range(self.num_agents):
                    for wall_idx, center in enumerate(sigwall_centers):
                        ca_wall = CollisionAvoidance(
                            f'ca_robot_{i}_sigwall_{wall_idx}',
                            robots[i],
                            None,
                            c=center,
                            R=sigwall_radius,
                            epsilon=1e-3,
                            alpha=1e-5,
                            eta=1.0,
                        )
                        sigwall_nodes.append(ca_wall)
            
            # [ADD 2026-04-18] 为每个机器人挂一个 RL 叶节点
            # 任务空间 = 机器人自身的 2D 位置 (与论文 4.3.1 一致: psi=I, J=I, M=w*I)
            # 初始 a_RL = 0, 每步由 apply_correction 调用 rl_leaf.set_action() 更新
            rl_nodes = []
            if self.fusion_mode == 'leaf':
                for i in range(self.num_agents):
                    rl_leaf = RLLeaf(
                        f'rl_env{env_idx}_robot_{i}',
                        robots[i],
                        w=self.rl_leaf_weight,
                        dim=2,
                    )
                    rl_nodes.append(rl_leaf)

            self.rmp_trees.append(r)
            self.rmp_robots.append(robots)
            self.rmp_collision_nodes.append(collision_nodes)
            self.rmp_formation_nodes.append(formation_nodes)
            self.rmp_sigwall_nodes.append(sigwall_nodes)
            self.rmp_rl_nodes.append(rl_nodes)  # [ADD 2026-04-18]
    
    def apply_correction(
        self,
        actions: list,
        agent_positions: list,
        agent_velocities: list,
        agent_headings: list = None,  # [ADD 2026-04-18 缺口 1] 每 agent 航向 (shape [n_envs])
    ) -> list:
        """
        使用 RMP 修正动作

        参数:
            actions: List[torch.Tensor], 每个 agent 的动作 [n_envs, action_dim]
            agent_positions: List[np.ndarray], 每个 agent 的位置 [n_envs, 2]
            agent_velocities: List[np.ndarray], 每个 agent 的速度 [n_envs, 2]
            agent_headings: 可选, List[np.ndarray], 每个 agent 的航向 θ [n_envs].
                若为 None 且 use_diff_drive_mapping=True, 降级使用速度方向估计.

        返回:
            corrected_actions: List[torch.Tensor], 修正后的动作
        """
        if not self.rmp_enabled or self.rmp_trees is None:
            return actions
        
        corrected_actions = []
        
        for env_idx in range(self.num_envs):
            # 构建状态向量 [x0, y0, x1, y1, ...]
            x = np.zeros((2 * self.num_agents, 1))
            x_dot = np.zeros((2 * self.num_agents, 1))
            
            for i in range(self.num_agents):
                pos = agent_positions[i][env_idx]
                vel = agent_velocities[i][env_idx]
                
                # 处理 torch.Tensor 或 numpy array
                if isinstance(pos, torch.Tensor):
                    pos = pos.cpu().numpy()
                if isinstance(vel, torch.Tensor):
                    vel = vel.cpu().numpy()
                
                x[2*i:2*i+2, 0] = pos[:2]  # 只取 x, y
                x_dot[2*i:2*i+2, 0] = vel[:2] if len(vel) >= 2 else np.zeros(2)
            
            # [ADD 2026-04-18] 若 fusion_mode='leaf', 先把当前 RL 动作注入各 RL 叶节点
            # —— 论文 4.3.1 对应实现: RL 叶节点参与根节点 pullback 合成
            if self.fusion_mode == 'leaf' and self.rmp_rl_nodes is not None:
                for i in range(self.num_agents):
                    a_rl_i = actions[i][env_idx]
                    if isinstance(a_rl_i, torch.Tensor):
                        a_rl_i = a_rl_i.detach().cpu().numpy()
                    a_rl_i = np.asarray(a_rl_i, dtype=np.float64).reshape(-1)
                    # RL 叶节点的任务空间 dim=2 (2D 位置加速度)
                    self.rmp_rl_nodes[env_idx][i].set_action(a_rl_i[:2])

            # 更新 RMP 树
            r = self.rmp_trees[env_idx]
            r.set_root_state(x, x_dot)
            r.pushforward()

            # 更新碰撞和编队节点
            for node in self.rmp_collision_nodes[env_idx]:
                node.update()
            for node in self.rmp_formation_nodes[env_idx]:
                node.update()
            # Sigwalls 为静态障碍物，其 psi/J 在初始化时已固定，
            # 这里只依赖于机器人位姿，因此无需在每步单独更新参数。
            # [ADD 2026-04-18] RL 叶节点的 psi/J 为常数 (identity),
            # 只需每步通过 set_action 更新 a_RL, 无需调用 update_params.

            r.pullback()

            # [MOD 2026-04-18] 解析得到合成加速度
            #   fusion_mode='leaf'     : resolve() 已将 RL 与几何力在根节点上同度量加权合成,
            #                            直接取对应机器人的分量作为最终动作.
            #   fusion_mode='additive' : 回退到旧版行为 (a_final = a_RL + rmp_weight * a_RMP).
            try:
                acceleration_correction = r.resolve()  # [2*num_agents, 1]

                env_corrected_actions = []
                for i in range(self.num_agents):
                    accel_corr = acceleration_correction[2*i:2*i+2, 0]

                    original_action = actions[i][env_idx]
                    if isinstance(original_action, torch.Tensor):
                        original_action = original_action.detach().cpu().numpy()

                    if self.fusion_mode == 'leaf':
                        # resolve() 输出 2D 世界坐标加速度 (ax, ay).
                        # [ADD 2026-04-18 缺口 1] 对接 chap4.4.4 差速映射:
                        #   env Point agent 的动作是机体系 (v, omega), 因此对 world-frame
                        #   (ax, ay) 做如下投影/朝向控制:
                        #     v = cos(θ) ax + sin(θ) ay
                        #     θ_d = atan2(ay, ax)
                        #     omega = k_θ * wrap(θ_d - θ)
                        if self.use_diff_drive_mapping and len(original_action) == 2:
                            ax = float(accel_corr[0])
                            ay = float(accel_corr[1])
                            # 获取当前航向 θ: 优先使用调用方传入的 agent_headings,
                            # 降级用速度方向估计 (静止时为 0, 由于 P 控器不会发散, 可接受)
                            if agent_headings is not None and len(agent_headings) > i:
                                th_arr = agent_headings[i]
                                theta = float(th_arr[env_idx]) if th_arr is not None and len(th_arr) > env_idx else 0.0
                            else:
                                vx, vy = float(agent_velocities[i][env_idx][0]), float(agent_velocities[i][env_idx][1])
                                theta = float(np.arctan2(vy, vx)) if (vx * vx + vy * vy) > 1e-6 else 0.0
                            v_cmd = np.cos(theta) * ax + np.sin(theta) * ay
                            # 仅当 (ax, ay) 模值非零时才取 atan2 (否则方向不定, 保持当前 θ)
                            if ax * ax + ay * ay > 1e-8:
                                theta_d = float(np.arctan2(ay, ax))
                                theta_err = (theta_d - theta + np.pi) % (2.0 * np.pi) - np.pi
                            else:
                                theta_err = 0.0
                            omega_cmd = self.diff_drive_k_theta * theta_err
                            # env action 空间通常是 [-1, 1], 做饱和保护
                            v_cmd = float(np.clip(v_cmd, -1.0, 1.0))
                            omega_cmd = float(np.clip(omega_cmd, -1.0, 1.0))
                            final_np = np.array([v_cmd, omega_cmd], dtype=original_action.dtype)
                        else:
                            # 映射关闭或动作维度非 2, 直接返回 resolve 输出
                            final_np = accel_corr[:len(original_action)].astype(original_action.dtype, copy=True)
                    else:
                        # 回退: 线性加权叠加 (legacy 行为)
                        final_np = original_action + self.rmp_weight * accel_corr[:len(original_action)]

                    env_corrected_actions.append(torch.from_numpy(final_np).to(self.device))

                if env_idx == 0:
                    corrected_actions = [[ac] for ac in env_corrected_actions]
                else:
                    for i in range(self.num_agents):
                        corrected_actions[i].append(env_corrected_actions[i])
            except Exception as e:
                # 若 RMP 求解失败 (奇异/数值异常), 回退到原始 RL 动作并打印警告
                print(f"Warning: RMP resolve failed at env {env_idx}: {e}. Using raw RL action.")
                if env_idx == 0:
                    corrected_actions = [[actions[i][env_idx]] for i in range(self.num_agents)]
                else:
                    for i in range(self.num_agents):
                        corrected_actions[i].append(actions[i][env_idx])
        
        # 转换为正确的格式
        final_actions = []
        for i in range(self.num_agents):
            final_actions.append(torch.stack(corrected_actions[i]))
        
        return final_actions
    
    def get_agent_positions_from_env(self, envs, n_envs: int) -> tuple:
        """
        从环境中获取 agent 位置和速度
        
        参数:
            envs: 向量化环境对象
            n_envs: 环境数量
        
        返回:
            (agent_positions, agent_velocities): 位置和速度列表
        """
        agent_positions = []
        agent_velocities = []
        agent_headings = []  # [ADD 2026-04-18 缺口 1] 每 agent 的 θ, 用于差速映射

        # 对于向量化环境，从每个子环境获取位置
        if hasattr(envs, 'envs') and len(envs.envs) > 0:
            # 向量化环境
            for env_idx in range(min(n_envs, len(envs.envs))):
                env = envs.envs[env_idx]
                if hasattr(env, 'env') and hasattr(env.env, 'task') and hasattr(env.env.task, 'agent'):
                    agent = env.env.task.agent
                    env_positions = []
                    env_velocities = []
                    env_headings = []
                    for i in range(self.num_agents):
                        # 获取 agent 位置（pos_0, pos_1, ...）
                        pos_attr = getattr(agent, f'pos_{i}', None)
                        if pos_attr is not None:
                            pos = pos_attr[:2]  # 只取 x, y
                        else:
                            pos = np.zeros(2)

                        # 获取 agent 速度（vel_0, vel_1, ...）
                        vel_attr = getattr(agent, f'vel_{i}', None)
                        if vel_attr is not None:
                            vel = vel_attr[:2]  # 只取 x, y 方向速度
                        else:
                            vel = np.zeros(2)

                        # [ADD 2026-04-18 缺口 1] 航向 θ = atan2(mat[1,0], mat[0,0])
                        mat_attr = getattr(agent, f'mat_{i}', None)
                        if mat_attr is not None:
                            theta = float(np.arctan2(mat_attr[1][0], mat_attr[0][0]))
                        else:
                            theta = 0.0

                        env_positions.append(pos)
                        env_velocities.append(vel)
                        env_headings.append(theta)

                    if env_idx == 0:
                        agent_positions = [[pos] for pos in env_positions]
                        agent_velocities = [[vel] for vel in env_velocities]
                        agent_headings = [[th] for th in env_headings]
                    else:
                        for i in range(self.num_agents):
                            agent_positions[i].append(env_positions[i])
                            agent_velocities[i].append(env_velocities[i])
                            agent_headings[i].append(env_headings[i])

            # 转换为 numpy 数组
            for i in range(self.num_agents):
                agent_positions[i] = np.array(agent_positions[i])
                agent_velocities[i] = np.array(agent_velocities[i])
                agent_headings[i] = np.array(agent_headings[i])
        else:
            # 如果无法获取，使用零向量作为占位符
            for i in range(self.num_agents):
                agent_positions.append(np.zeros((n_envs, 2)))
                agent_velocities.append(np.zeros((n_envs, 2)))
                agent_headings.append(np.zeros((n_envs,)))

        return agent_positions, agent_velocities, agent_headings
